---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      customize:
        memory: 2048
        cpus: 2
    run_list:
      - recipe[apt]
  - name: ubuntu-10.04
    driver_config:
      customize:
        memory: 2048
        cpus: 2
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[drupal::default]
    attributes:
      mysql:
        server_root_password: 'root'
        server_debian_password: 'root'
        server_repl_password: 'root'
        allow_remote_root: true
        bind_address: '0.0.0.0'
      apache:
        listen_ports: ['8080']
        default_site_enabled: false
      nginx:
        default_site_enabled: false
