---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: lucid64
    driver_config:
      box: "lucid64"
      box_url: "http://files.vagrantup.com/lucid64.box"
      customize:
        memory: 2048
        cpus: 2
      network:
        - ["private_network", {ip: "33.33.33.10"}]
    run_list:
      - recipe[apt]
  - name: precise64
    driver_config:
      box: "precise64"
      box_url: "http://files.vagrantup.com/precise64.box"
      customize:
        memory: 2048
        cpus: 2
      network:
        - ["private_network", {ip: "33.33.33.10"}]
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[drupal::default]
    attributes:
      mysql:
        server_root_password: 'root'
        server_debian_password: 'root'
        server_repl_password: 'root'
        allow_remote_root: true
        bind_address: '0.0.0.0'
      apache:
        listen_ports: ['8080']
        default_site_enabled: false
      nginx:
        default_site_enabled: false
      drupal:
        docroot: '/vagrant/public'
