---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[drupal::default]
    attributes:
