name             'drupal'
maintainer       'James Walker'
maintainer_email 'walkah@walkah.net'
license          'Apache 2.0'
description      'Installs/Configures Drupal'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'

supports 'debian'
supports 'ubuntu'

depends 'apache2',            '~> 1.8.14'
depends 'apt',                '~> 2.3.4'
depends 'build-essential',    '~> 1.4.2'
depends 'database',           '~> 2.0.0'
depends 'drush'
depends 'git',                '~> 2.9.0'
depends 'mysql',              '~> 4.0.20'
depends 'nginx',              '~> 2.4.2'
depends 'php',                '~> 1.4.4'
