name 'drupal'
maintainer 'James Walker'
maintainer_email 'walkah@walkah.net'
license 'Apache 2.0'
description 'Installs/Configures Drupal'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.3.0'

supports 'debian'
supports 'ubuntu'

depends 'apache2'
depends 'apt'
depends 'build-essential'
depends 'database'
depends 'drush'
depends 'git'
depends 'mysql'
depends 'mysql2_chef_gem'
depends 'nginx'
depends 'php'
